#!/usr/bin/env bash

function _docker_machine_profile {
  local shome="${_docker_machine_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  DOCKER_MACHINE_VERSION=0.12.1
}

_docker_machine_profile
