#!/usr/bin/env bash

function version {
  local shome="${_docker_machine_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local ver_machine="$(docker-machine --version 2>/dev/null | awk 'NR == 1 {print $3}' | perl -pe 's{,$}{}' || true)"
  jq -n \
    --arg machine "$ver_machine" \
    '{"docker-machine": $machine}'
}

version "$@"
